# Generated by Django 2.1.8 on 2019-07-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=511)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Article')),
            ],
            options={
                'db_table': 'ar_photo',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('ch_name', models.CharField(blank=True, max_length=128, null=True)),
                ('en_name', models.CharField(blank=True, max_length=128, null=True)),
                ('alias', models.CharField(blank=True, max_length=128, null=True)),
                ('shape', models.CharField(blank=True, max_length=128, null=True)),
                ('origin', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cat_like', models.CharField(blank=True, max_length=128, null=True)),
                ('cat_character', models.CharField(blank=True, max_length=128, null=True)),
                ('sti_degree', models.IntegerField(blank=True, null=True)),
                ('bar_degree', models.IntegerField(blank=True, null=True)),
                ('hair_loss_degree', models.IntegerField(blank=True, null=True)),
                ('fri_degree', models.IntegerField(blank=True, null=True)),
                ('ani_fri_degree', models.IntegerField(blank=True, null=True)),
                ('trainability', models.IntegerField(blank=True, null=True)),
                ('city_degree', models.IntegerField(blank=True, null=True)),
                ('feature', models.CharField(blank=True, max_length=128, null=True)),
                ('attention', models.CharField(blank=True, max_length=128, null=True)),
                ('nurturing_knowledge', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='CatArticle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=128)),
                ('article_pic', models.CharField(max_length=128)),
                ('article_content', models.CharField(max_length=12800)),
            ],
            options={
                'db_table': 'cat_article',
            },
        ),
        migrations.CreateModel(
            name='CatDisease',
            fields=[
                ('cat_dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_name', models.CharField(max_length=128)),
                ('performace', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'cat_disease',
            },
        ),
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('cp_name', models.CharField(max_length=128)),
                ('cp_category', models.CharField(max_length=128)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Cat')),
            ],
            options={
                'db_table': 'cat_photo',
            },
        ),
        migrations.CreateModel(
            name='CatVari',
            fields=[
                ('cati_id', models.AutoField(primary_key=True, serialize=False)),
                ('vari_name', models.CharField(blank=True, max_length=128, null=True)),
                ('cat_vari_img', models.CharField(blank=True, max_length=128, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c', to='common.Cat')),
            ],
            options={
                'db_table': 'cat_vari',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('col_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_content', models.CharField(max_length=511)),
                ('c_time', models.DateTimeField(blank=True, null=True)),
                ('c_counts', models.IntegerField(blank=True, null=True)),
                ('com_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Comment')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
                ('ch_name', models.CharField(max_length=128)),
                ('en_name', models.CharField(max_length=128)),
                ('origin', models.CharField(blank=True, max_length=128, null=True)),
                ('shape', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('sti_degree', models.IntegerField(blank=True, null=True)),
                ('bar_degree', models.IntegerField(blank=True, null=True)),
                ('hairloss_degree', models.IntegerField(blank=True, null=True)),
                ('fri_degree', models.IntegerField(blank=True, null=True)),
                ('stranger_frii_degree', models.IntegerField(blank=True, null=True)),
                ('compliance', models.IntegerField(blank=True, null=True)),
                ('home_degree', models.IntegerField(blank=True, null=True)),
                ('feature', models.CharField(blank=True, max_length=128, null=True)),
                ('attention', models.CharField(blank=True, max_length=128, null=True)),
                ('nurturing_knowledge', models.CharField(blank=True, max_length=511, null=True)),
            ],
            options={
                'db_table': 'dog',
            },
        ),
        migrations.CreateModel(
            name='DogArticle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=128)),
                ('article_pic', models.CharField(max_length=128)),
                ('article_content', models.CharField(max_length=12800)),
            ],
            options={
                'db_table': 'dog_article',
            },
        ),
        migrations.CreateModel(
            name='DogDisease',
            fields=[
                ('dog_dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_name', models.CharField(max_length=128)),
                ('dis_code', models.CharField(max_length=128)),
                ('performace', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'dog_dissease',
            },
        ),
        migrations.CreateModel(
            name='DogDiseaseMedicine',
            fields=[
                ('ddm_id', models.AutoField(primary_key=True, serialize=False)),
                ('dog_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='m_d', to='common.DogDisease')),
            ],
            options={
                'db_table': 'dm_dis',
            },
        ),
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('dp_id', models.AutoField(primary_key=True, serialize=False)),
                ('dp_name', models.CharField(max_length=128)),
                ('dp_path', models.CharField(max_length=128)),
                ('dp_category', models.CharField(max_length=128)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Dog')),
            ],
            options={
                'db_table': 'dog_photo',
            },
        ),
        migrations.CreateModel(
            name='DogVari',
            fields=[
                ('dog_vari_id', models.AutoField(primary_key=True, serialize=False)),
                ('dog_vari_name', models.CharField(blank=True, max_length=128, null=True)),
                ('dog_vari_img', models.CharField(blank=True, max_length=128, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Dog')),
            ],
            options={
                'db_table': 'dog_vari',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.CharField(max_length=128)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('g_counts', models.IntegerField(blank=True, null=True)),
                ('is_public', models.IntegerField()),
            ],
            options={
                'db_table': 'dynamic',
            },
        ),
        migrations.CreateModel(
            name='DynamicCollection',
            fields=[
                ('dc_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='col', to='common.Collection')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dy0', to='common.Dynamic')),
            ],
            options={
                'db_table': 'd_collection',
            },
        ),
        migrations.CreateModel(
            name='DynamicTag',
            fields=[
                ('dt_id', models.AutoField(primary_key=True, serialize=False)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dy1', to='common.Dynamic')),
            ],
            options={
                'db_table': 'd_tag',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(blank=True, max_length=128, null=True)),
                ('m_function', models.CharField(blank=True, max_length=128, null=True)),
                ('m_explain', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('addr', models.CharField(blank=True, max_length=128, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.CharField(blank=True, max_length=128, null=True)),
                ('qua_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='MedicineDis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='m_c', to='common.CatDisease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c_med', to='common.Medicine')),
            ],
            options={
                'db_table': 'm_dis',
            },
        ),
        migrations.CreateModel(
            name='Nice',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nice_c', to='common.Comment')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nice_d', to='common.Dynamic')),
            ],
            options={
                'db_table': 'tb_nice',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=128)),
                ('p_code', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'pemission',
            },
        ),
        migrations.CreateModel(
            name='PetDoctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=128)),
                ('sex', models.IntegerField()),
                ('years', models.IntegerField()),
                ('area', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'petdoctor',
            },
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=128)),
                ('p_type', models.IntegerField()),
                ('p_birthday', models.DateTimeField(blank=True, null=True)),
                ('verities', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'pet_info',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_path', models.CharField(max_length=128)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Dynamic')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(blank=True, max_length=128, null=True)),
                ('r_code', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('rp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pemission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='per', to='common.Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_r', to='common.Role')),
            ],
            options={
                'db_table': 'r_p',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_content', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=128)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('u_password', models.CharField(max_length=128)),
                ('addres', models.CharField(blank=True, max_length=128, null=True)),
                ('tel', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('icon', models.CharField(blank=True, max_length=128, null=True)),
                ('sign', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.IntegerField(default=1)),
                ('realname', models.CharField(blank=True, max_length=128, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('lastvisit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserFlowing',
            fields=[
                ('u_following_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('following_id', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'user_flowing',
            },
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('u_follower_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('follower_id', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'user_flower',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('ur_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='common.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='u_r', to='common.User')),
            ],
            options={
                'db_table': 'u_r',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('tokenid', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
                ('user', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.PROTECT, to='common.User')),
            ],
            options={
                'db_table': 'tb_user_token',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(through='common.UserRole', to='common.Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(through='common.RolePermission', to='common.Permission'),
        ),
        migrations.AddField(
            model_name='petinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.User'),
        ),
        migrations.AddField(
            model_name='nice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nice_u', to='common.User'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cat_disease',
            field=models.ManyToManyField(through='common.MedicineDis', to='common.CatDisease'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dog_disease',
            field=models.ManyToManyField(through='common.DogDiseaseMedicine', to='common.DogDisease'),
        ),
        migrations.AddField(
            model_name='dynamictag',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='ta', to='common.Tag'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='tag',
            field=models.ManyToManyField(related_name='tag_dynamic', through='common.DynamicTag', to='common.Tag'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.User'),
        ),
        migrations.AddField(
            model_name='dogdiseasemedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d_med', to='common.Medicine'),
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_vari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dv', to='common.DogVari'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Dynamic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='dynamic',
            field=models.ManyToManyField(related_name='dy2', through='common.DynamicCollection', to='common.Dynamic'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.User'),
        ),
        migrations.AddField(
            model_name='cat',
            name='catvari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cv', to='common.CatVari'),
        ),
    ]
