# Generated by Django 2.1.8 on 2019-07-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='catvari',
        ),
        migrations.RemoveField(
            model_name='catvari',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='dogvari',
            name='dog',
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_vari',
            field=models.OneToOneField(db_column='dog_vari_id', on_delete=django.db.models.deletion.PROTECT, to='common.DogVari'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=511),
        ),
    ]
