# Generated by Django 2.1.8 on 2019-07-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190708_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dog_vari',
        ),
        migrations.RemoveField(
            model_name='catphoto',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='catphoto',
            name='cp_category',
        ),
        migrations.RemoveField(
            model_name='catphoto',
            name='cp_name',
        ),
        migrations.RemoveField(
            model_name='dogphoto',
            name='dp_category',
        ),
        migrations.RemoveField(
            model_name='dogphoto',
            name='dp_name',
        ),
        migrations.AddField(
            model_name='catphoto',
            name='catvari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.CatVari'),
        ),
        migrations.AddField(
            model_name='catvari',
            name='ani_fri_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='attention',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='bar_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='cat_character',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='cat_like',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='city_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='en_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='feature',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='fri_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='hair_loss_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='nurturing_knowledge',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='shape',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='sti_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='trainability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catvari',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='attention',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='bar_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='compliance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='en_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='feature',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='fri_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='hairloss_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='home_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='nurturing_knowledge',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='shape',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='sti_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='stranger_frii_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catdisease',
            name='dis_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dogphoto',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.DogVari'),
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
