# Generated by Django 2.1.8 on 2019-07-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190708_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogphoto',
            name='dog',
        ),
        migrations.AddField(
            model_name='catvari',
            name='alias',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='dogvari',
            field=models.ForeignKey(blank=True, db_column='dogvari', null=True, on_delete=django.db.models.deletion.PROTECT, to='common.DogVari'),
        ),
        migrations.AddField(
            model_name='dogvari',
            name='alias',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='en_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='origin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='shape',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='vari_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dogvari',
            name='dog_vari_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dogvari',
            name='en_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dogvari',
            name='origin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dogvari',
            name='shape',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
