# Generated by Django 2.1.8 on 2019-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190708_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catvari',
            name='cat_character',
        ),
        migrations.RemoveField(
            model_name='catvari',
            name='cat_like',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='tag',
        ),
        migrations.AddField(
            model_name='catvari',
            name='cat_habit',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='tags',
            field=models.ManyToManyField(through='common.DynamicTag', to='common.Tag'),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='attention',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='feature',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
        migrations.AlterField(
            model_name='catvari',
            name='nurturing_knowledge',
            field=models.CharField(blank=True, max_length=2560, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
