# Generated by Django 2.1.8 on 2019-07-11 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiccollection',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='dynamiccollection',
            name='dynamic',
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='nice',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='dynamic',
        ),
        migrations.AddField(
            model_name='collection',
            name='dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Dynamic'),
        ),
        migrations.DeleteModel(
            name='DynamicCollection',
        ),
    ]
