# Generated by Django 2.1.8 on 2019-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20190711_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='col_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userflowing',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
